---
title: "&nbsp;"
---


<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
td {  /* Table  */
  font-size: 8px;
}
h1.title {
  font-size: 48px;
  font-weight: bold;
  color:#1f618d;
  font-family: Tahoma, sans-serif
}

h2 {
  font-size: 30px;
  font-weight: bold;
  color:#1f618d;
  font-family: Tahoma, sans-serif
}


div.blue { background-color:#f0fbfc ; border-radius: 4px; padding: 10px;}

</style>

<br>



<iframe width="1000" height="600 border: 6px" src="title.html"></iframe>

<br>


### Objective
<div class = "blue">
The purpose of this website is to provide brief, practical advice to people wanting to better integrate data science into their conservation and development projects. 
</div>

<br>

In order to help individuals and organisations associated with the Minderoo Foundation achieve that goal I have assembled a set of support materials to cover the major concepts covered in the workshop course.

<br>

### Support materials
* [Workshop slides](slides.html)
* [How to build a basic strategy](strategy.html)
* [Science - the basics](science.html)
* [Additional resources](resources.html)

<br>

### About the creator

The materials in this course were created by Nathan Whitmore, a conservation scientist and practitioner. Over the years he has worked variously as a fisheries observer, conservation ranger, and, from 2012 to 2018, as an in-country adviser for the Wildlife Conservation Society’s Papua New Guinea programme. He is currently based in New Zealand where he runs [Reproducible](reproducible.co.nz),  a small conservation consultancy. Reproducible focuses on various aspects of data integration including staff and organisation training, study design and simulation, and the development of automated data analyses for project level data.
