---
title: 'Science: the basics'
---


<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
td {  /* Table  */
  font-size: 8px;
}
h1.title {
  font-size: 48px;
  font-weight: bold;
  color:#1f618d;
  font-family: Tahoma, sans-serif
}

h2 {
  font-size: 30px;
  font-weight: bold;
  color:#1f618d;
  font-family: Tahoma, sans-serif
}


div.blue { background-color:#f0fbfc ; border-radius: 4px; padding: 10px;}

</style>

<br>


## What is science?
<div class = "blue">
Science is a provisional belief system. 
</div>
<br>

Science differs from other belief systems in that scientific knowledge is under a constant process of revision. Existing knowledge can be revised, reinforced, or wholly rejected based on the demonstration of observable, reproducible, evidence.

By this definition knowledge which cannot be updated can not be scientific. This is known as the *falsification principle* which is used to separate science from non-science.

<br>

### What is evidence?
<div class = "blue">
Evidence is an observation that is consistent with a certain idea being true.
</div>

<br>

In science this evidence needs to be observable, and reproducible (meaning it can be reproduced independently by other people following the same process).

<br>

### Scientific method
<div class = "blue">
One way to generate scientific knowledge is through a formalised 3-step process called the *scientific method*. 
</div>
<br>

The three steps are:

1. **Hypothesis**: in which the person or group comes up with an idea of the system might behaviour. 
2. **Experiment**: in which the person or group manipulates the system and see how it responds.
2. **Evaluation**: in which the person or group judges whether or not the system responded in a way consistent with their hypothesis. Based on whether or not their experimental evidence supported their hypothesis they update their beliefs.

<br>
Central to the scientific method is the manipulation of a system through an experiment. While the scientific method is one way of generating scientific knowledge it is not the only way. Scientific knowledge can also be gained by unplanned observation, without the requirement for a preconceived hypothesis or formal experiment.

<br>

So, while the scientific method is a way to gain scientific knowledge it is not the only way.



